### ISSUE TITLE
Request for Model and Checkpoint

### ISSUE THREAD

**Issue by limumm** [open-vision-language/oven#3]
Hello, I am very interested in your work after reading the paper. I want to reproduce the experimental results in the paper. Could you please share the model and training checkpoints shown in the paper, especially the **CLIP Fusion** that performed best on Entity Split SEEN? Thank you very much!

**Comment by edchengg** [comment]
Hi limumm, sorry for late response. I was busy with CVPR and conference traveling.
Unfortunately, I am not able to provide checkpoints.
We have a follow up work which built a multimodal retriever using CLIP at: https://github.com/TIGER-AI-Lab/UniIR on OVEN.
The model and dataset split will be released asap.
