### ISSUE TITLE
Request for the super-category grouping information of answer for each sample

### ISSUE THREAD

**Issue by kaipochang0810** [open-vision-language/oven#4]
Thanks for your excellent work. I am very appreciated your work after reading the paper! I want to understand the super-category of answer in each sample of OVEN. Could you please share the file(s) that are used to visualize the distribution of the entities in OVEN in Figure 8? If possible, I also want to know the actual super-category of the answer that belongs to "others" type. Thank you very much!

**Comment by edchengg** [comment]
Hi @kaipochang0810,
Thanks for your interest! I don't have the super category file. 
One workaround is to extract the super category from the "question" using simple heuristics.
